name: Test
run-name: Test main - ${{ inputs.sha == github.sha || inputs.sha == ''}}
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA'
        required: false
        default: ''

jobs:
  Test:
    name: Test [run on main - ${{ inputs.sha == github.sha || inputs.sha == ''}}]
    runs-on: ubuntu-latest
    steps:
      - name: Check
        shell: pwsh
        run: |
          Write-Host "GitHub SHA: ${{ github.sha }}"
          Write-Host "Input SHA: ${{ github.event.inputs.sha }}"
          
