name: Update BC Artifact Version

on:
  workflow_dispatch:
  schedule:
    - cron: '55 5 * * *' # Daily at 05:55 UTC

defaults:
  run:
    shell: powershell

permissions: read-all

jobs:
  GetBranches:
    name: Get Official Branches
    runs-on: ubuntu-latest
    outputs:
      UpdateBranches: ${{ steps.OfficialBranches.outputs.OfficialBranches }}
    steps:
      - name: Get Official Branches
        id: OfficialBranches
        uses: microsoft/BCApps/.github/actions/GetOfficialBranches@mazhelez/restructure-automations

  UpdateBCArtifactVersion:
    name: "[${{ matrix.branch }}] Update BC Artifact Version"
    permissions:
      contents: write
    environment: Official-Build
    runs-on: windows-latest
    needs: GetBranches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.GetBranches.outputs.UpdateBranches) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Update BC Artifact Version
        env:
          GH_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
        uses: microsoft/BCApps/.github/actions/RunAutomation@mazhelez/restructure-automations
        with:
          automations: UpdateBCArtifact
          targetBranch: ${{ matrix.branch }}
