name: Update BC Artifact Version

on:
  workflow_dispatch:
  schedule:
    - cron: '55 5 * * *' # Daily at 05:55 UTC

defaults:
  run:
    shell: powershell

jobs:
  GetBranches:
    name: Get Official Branches
    runs-on: windows-latest
    outputs:
      UpdateBranches: ${{ steps.OfficialBranches.outputs.OfficialBranches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Official Branches
        id: OfficialBranches
        uses: ./.github/actions/GetOfficialBranches

  UpdateBCArtifactVersion:
    name: "[${{ matrix.branch }}] Update BC Artifact Version"
    permissions:
      contents: write
    environment: Official-Build
    runs-on: windows-latest
    needs: GetBranches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.GetBranches.outputs.UpdateBranches) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Update BC Artifact Version
        env:
          GH_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
        run: |
            build/scripts/Automations/run.ps1 -Include 'UpdateBCArtifact' -Repository $ENV:GITHUB_REPOSITORY -TargetBranch ${{ matrix.branch }} -Actor $env:GITHUB_ACTOR