name: Update AL-Go On Official Branches

on:
  workflow_dispatch:
  schedule:
    - cron: "55 08 * * 3" # Run at 08:55 UTC on Wednesday

jobs:
  GetBranches:
    name: Get Official Branches
    runs-on: ubuntu-latest
    outputs:
      UpdateBranches: ${{ steps.OfficialBranches.outputs.OfficialBranches }}
    steps:
      - name: Get Official Branches
        id: OfficialBranches
        uses: microsoft/BCApps/.github/actions/GetOfficialBranches@mazhelez/restructure-automations

  UpdateALGo:
    name: "[${{ matrix.branch }}] Update AL-Go"
    runs-on: ubuntu-latest
    environment: Official-Build
    needs: GetBranches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.GetBranches.outputs.UpdateBranches) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Update AL-Go System Files
        env:
          GH_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
        uses: microsoft/BCApps/.github/actions/RunAutomation@mazhelez/restructure-automations
        with:
          automations: UpdateALGo
          targetBranch: ${{ matrix.branch }}
